sudo: required

language: generic

services:
  - docker

before_script:
  - docker pull spack/spack.io

script:
  - docker build --cache-from spack/spack.io -t spack/spack.io .
  - if [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then
      if echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; then
        docker push spack/spack.io;
      fi;
    fi
