# Setup
image:        /img/spack-logo-white.svg
title:        Spack

tagline:      |
  A flexible package manager that supports multiple versions,
  configurations, platforms, and compilers.

baseurl:      ""

# About/contact
author:
  name:       the Spack community
  url:        http://github.com/LLNL/spack

paginate: 1

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown
